Fix `golangci-lint config verify` error
```
Error: Failed to run: Error: Command failed: /home/runner/golangci-lint-1.64.7-linux-amd64/golangci-lint config verify
jsonschema: "linters-settings.testifylint" does not validate with "/properties/linters-settings/properties/testifylint/type": got null, want object
jsonschema: "linters-settings.wrapcheck" does not validate with "/properties/linters-settings/properties/wrapcheck/type": got null, want object
jsonschema: "linters-settings.gofmt" does not validate with "/properties/linters-settings/properties/gofmt/type": got null, want object
Failed executing command with error: the configuration contains invalid elements
, Error: Command failed: /home/runner/golangci-lint-1.64.7-linux-amd64/golangci-lint config verify
jsonschema: "linters-settings.testifylint" does not validate with "/properties/linters-settings/properties/testifylint/type": got null, want object
jsonschema: "linters-settings.wrapcheck" does not validate with "/properties/linters-settings/properties/wrapcheck/type": got null, want object
jsonschema: "linters-settings.gofmt" does not validate with "/properties/linters-settings/properties/gofmt/type": got null, want object
```